use_frameworks!

platform :ios, '9.0'

target 'IFImageBrowserKit_Example' do
  pod 'IFImageBrowserKit', :path => '../'

  target 'IFImageBrowserKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
